begin;

create table if not exists public.tickets_ganadores (
  id bigint generated by default as identity primary key,
  archivo text not null
    check (archivo ~ '^ticket_[0-9]{1,20}[.]jpg$'),
  caption text not null default 'Ticket Ganador'
    check (char_length(caption) between 1 and 1000),
  file_id text not null
    check (file_id ~ '^[A-Za-z0-9_-]{1,512}$'),
  file_unique_id text not null default ''
    check (file_unique_id = '' or file_unique_id ~ '^[A-Za-z0-9_-]{1,512}$'),
  telegram_chat_id bigint not null
    check (telegram_chat_id <> 0),
  received_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.tickets_ganadores
  add column if not exists telegram_chat_id bigint,
  add column if not exists file_unique_id text,
  add column if not exists received_at timestamptz not null default now();

create index if not exists tickets_ganadores_admin_received_at_idx
  on public.tickets_ganadores (telegram_chat_id, received_at);

alter table public.tickets_ganadores enable row level security;

revoke all on table public.tickets_ganadores
  from public, anon, authenticated, service_role;
grant select, insert on table public.tickets_ganadores
  to service_role;

do $$
begin
  if to_regclass('public.tickets_ganadores_id_seq') is not null then
    execute 'revoke all on sequence public.tickets_ganadores_id_seq '
      || 'from public, anon, authenticated, service_role';
    execute 'grant usage, select on sequence public.tickets_ganadores_id_seq '
      || 'to service_role';
  end if;
end
$$;

commit;
