begin;

-- Fresh projects do not contain application tables. Establish the narrow base
-- required by the membership, run-ledger and source-audit migrations that
-- follow. Every upgrade alteration is additive and preserves existing rows.
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'user',
    telegram_id text,
    telegram_username text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.profiles
    add column if not exists role text not null default 'user';
alter table public.profiles
    add column if not exists telegram_id text;
alter table public.profiles
    add column if not exists telegram_username text;
alter table public.profiles
    add column if not exists created_at timestamptz not null default now();
alter table public.profiles
    add column if not exists updated_at timestamptz not null default now();

-- An existing installation may predate the auth relationship. NOT VALID keeps
-- orphaned historical rows readable while enforcing the FK for new writes.
do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.profiles'::regclass
          and confrelid = 'auth.users'::regclass
          and contype = 'f'
    ) then
        alter table public.profiles
            add constraint profiles_id_auth_user_fk
            foreign key (id) references auth.users(id) on delete cascade
            not valid;
    end if;
end
$$;

create table if not exists public.picks (
    id bigint generated by default as identity primary key,
    categoria text,
    partido text,
    pick text,
    cuota numeric,
    confianza text,
    razonamiento text,
    marcador text,
    estado text not null default 'pendiente',
    es_parlay boolean not null default false,
    liga text,
    mercado text,
    riesgo text,
    resultado_apuesta text,
    ganancia_simulada numeric not null default 0,
    fecha_generacion date,
    odds_mercado numeric,
    tiene_valor boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.picks
    add column if not exists categoria text,
    add column if not exists partido text,
    add column if not exists pick text,
    add column if not exists cuota numeric,
    add column if not exists confianza text,
    add column if not exists razonamiento text,
    add column if not exists marcador text,
    add column if not exists estado text not null default 'pendiente',
    add column if not exists es_parlay boolean not null default false,
    add column if not exists liga text,
    add column if not exists mercado text,
    add column if not exists riesgo text,
    add column if not exists resultado_apuesta text,
    add column if not exists ganancia_simulada numeric not null default 0,
    add column if not exists fecha_generacion date,
    add column if not exists odds_mercado numeric,
    add column if not exists tiene_valor boolean not null default false,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

commit;
